package it.unibo.apice.frameworkfv;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.JFrame;

/**
 * @author eoliva
 * @author Danilo Pianini
 * 
 */
public class JavaFV extends javax.swing.JFrame implements ActionListener {

	private static final String CNAME = "FVDynamicClass";
	private static final long serialVersionUID = 9129270147061546136L;

	/** Creates new form NewJFrame */
	public JavaFV() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jPanel3 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		getContentPane().setLayout(new java.awt.GridLayout(2, 1));
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		jPanel1.setLayout(new java.awt.GridLayout(1, 1));
		jScrollPane1.setBorder(new javax.swing.border.TitledBorder("Espressioni da valutare"));
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);
		jPanel1.add(jScrollPane1);
		jScrollPane2.setBorder(new javax.swing.border.TitledBorder("Espressione da valutare"));
		jTextArea2.setRows(3);
		jScrollPane2.setViewportView(jTextArea2);
		getContentPane().add(jPanel1);
		jPanel3.setLayout(new java.awt.BorderLayout());
		jButton1.setText("Valutazione");
		jButton1.addActionListener(this);
		jPanel2.add(jButton1);
		jPanel3.add(jPanel2, java.awt.BorderLayout.NORTH);
		jScrollPane3.setBorder(null);
		jScrollPane3.setViewportBorder(new javax.swing.border.TitledBorder("Risultato della valutazione"));
		jTextArea3.setRows(2);
		jScrollPane3.setViewportView(jTextArea3);
		jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);
		jTextArea1.setFont(new Font("Monospaced", Font.BOLD, 15));
		jTextArea1.setTabSize(2);
		jTextArea2.setFont(new Font("Monospaced", Font.BOLD, 15));
		jTextArea2.setTabSize(2);
		jTextArea3.setFont(new Font("Monospaced", Font.BOLD, 15));
		jTextArea3.setTabSize(2);
		getContentPane().add(jPanel3);
		pack();
	}

	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;

	private void showMsg(String msg) {
		jTextArea3.setText(msg);
	}

	private void doRun() throws IOException {
		final StringBuilder sb = new StringBuilder();
		sb.append("public class " + CNAME + " {\n");
		sb.append("\tpublic static String getResult (){\n");
		sb.append("\t\treturn \"\"+");
		sb.append("( ");
		sb.append(jTextArea1.getText());
		sb.append(" )");
		sb.append(";\n");
		sb.append("\t}\n");
		sb.append("}");
		showMsg(DynaComp.interpret(CNAME, sb.toString()));
		
	}

	/**
	 * Listens to actions from the run button.
	 */
	public void actionPerformed(ActionEvent e) {
		Object source = e.getSource();

		if (jButton1 == source) {
			// Disable the run button while we're running

			jButton1.setEnabled(false);
			try {
				doRun();
			} catch (IOException ex) {
				ex.printStackTrace();
			}
			jButton1.setEnabled(true);
		}
	}

	public static void main(String args[]) {
		JFrame f = new JavaFV();
		f.setTitle("Framework F-V");
		f.setBounds(100, 30, 800, 700);
		f.setVisible(true);
		f.validate();
	}

}
