package it.unibo.frameworkfv;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.BoxLayout;
import javax.swing.JFrame;

import static it.unibo.frameworkfv.Constants.FONT_SIZE;

/**
 * @author eoliva
 * @author Danilo Pianini
 * 
 *         Created on 29-ott-2005 Modified on Jan 11th, 2013
 */
public class JavaFF extends javax.swing.JFrame implements ActionListener {
	private static final String CNAME = "FrameworkFF";
	private static final long serialVersionUID = 7491470300619903100L;

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		JFrame f = new JavaFF();
		f.setTitle("Framework F-F "+Constants.VERSION);
		f.setBounds(100, 30, 800, 700);
		f.setVisible(true);

		f.validate();
	}

	private javax.swing.JButton jButton1;

	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;

	/** Creates new form NewJFrame */
	public JavaFF() {
		initComponents();
	}

	/**
	 * Listens to actions from the run button.
	 */
	public void actionPerformed(ActionEvent e) {
		Object source = e.getSource();
		if (jButton1 == source) {
			jButton1.setEnabled(false);
			doRun();
			jButton1.setEnabled(true);
		}
	}

	private void doRun() {
		final StringBuilder sb = new StringBuilder();
		sb.append("public class " + CNAME + " {");
		sb.append("\n\t");
		sb.append(jTextArea1.getText());
		sb.append("\n\tpublic String getResult(){");
		sb.append("\n\t\treturn \"\" ");
		if (jTextArea2.getText().compareTo("") != 0) {
			sb.append("+(");
			sb.append(jTextArea2.getText());
			sb.append(")");
		}
		sb.append(";\n\t}\n}");

		showMsg(DynaComp.interpret(CNAME, sb.toString()));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">
	private void initComponents() {
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jPanel3 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();

		getContentPane().setLayout(new java.awt.GridLayout(2, 1));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		jPanel1.setLayout(new java.awt.GridLayout(1, 1));

		jScrollPane1.setBorder(new javax.swing.border.TitledBorder("Dichiarazione di funzioni"));
		jTextArea1.setRows(4);
		jScrollPane1.setViewportView(jTextArea1);

		jPanel1.add(jScrollPane1);

		jScrollPane2.setBorder(new javax.swing.border.TitledBorder("Espressione da valutare"));
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));

		jPanel3.add(jScrollPane2);

		getContentPane().add(jPanel1);

		jButton1.setText("Valutazione");

		jButton1.addActionListener(this);
		jPanel2.add(jButton1);
		jPanel2.validate();

		jPanel3.add(jPanel2);

		jScrollPane3.setBorder(null);
		jScrollPane3.setViewportBorder(new javax.swing.border.TitledBorder("Risultato della valutazione"));
		jTextArea3.setRows(8);
		jScrollPane3.setViewportView(jTextArea3);

		jPanel3.add(jScrollPane3);

		jTextArea1.setFont(new Font("Monospaced", Font.BOLD, FONT_SIZE));
		jTextArea1.setTabSize(2);
		jTextArea2.setFont(new Font("Monospaced", Font.BOLD, FONT_SIZE));
		jTextArea2.setTabSize(2);
		jTextArea3.setFont(new Font("Monospaced", Font.BOLD, FONT_SIZE));
		jTextArea3.setTabSize(2);
		jTextArea3.setEditable(false);

		getContentPane().add(jPanel3);

		pack();
	}

	private void showMsg(String msg) {
		jTextArea3.setFont(new Font("Monospaced", Font.BOLD, 15));
		jTextArea3.setText(msg);
		jTextArea3.setCaretPosition(0);
	}

}
